version: '3.4'

networks:
  dev:
    driver: bridge
  
  service:
    api-key:
      image:
      depends_on:
        - "app_db"
      container_name: demoapp-service
      ports:
        - "8080:80"
      build:
        context: .
        dockerfile: dockerfile
      environment:
        - ConnectionStrings_DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=DemoApiKey; IntegratedSecurity=true;
        - ASPNETCORE_URLS=http://+:80
      networks:
        - dev
    app_db:
      image: postgres:lastest
      container_name: app_db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=DemoApiKey
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - app_data:/var/lib/postgresql/data
      networks:
        - dev
        
    volumes:
      app_data:
